In [1]:
import numpy as np 
import pandas as pd

In [82]:
#topics covered - head() - describe() - drop() -inplace=True() sort_index etc.

In [2]:
print("working")

working

In [3]:
dict1 = {
       "name" : ['pushpak','sandeep','akshat','ayushi'],
       "makrs" : [92,98,97,100],
       "city" :['indore','ujjain','dewas','bhopal']
}

In [4]:
df = pd.DataFrame(dict1)

In [5]:
df

      name  makrs    city
0  pushpak     92  indore
1  sandeep     98  ujjain
2   akshat     97   dewas
3   ayushi    100  bhopal

In [6]:
df.head(2) #shows top rows&coulumns

      name  makrs    city
0  pushpak     92  indore
1  sandeep     98  ujjain

In [7]:
df.to_csv('pandas.csv') #convert file into csv format(excel)

In [8]:
df.to_csv('pandas_indexFalse.csv',index=False)

In [9]:
df.head(2) #shows bottom 2 rowns and comlumns

      name  makrs    city
0  pushpak     92  indore
1  sandeep     98  ujjain

In [10]:
df.describe() #give numerical statistical things like mean mode median etc.

           makrs
count    4.00000
mean    96.75000
std      3.40343
min     92.00000
25%     95.75000
50%     97.50000
75%     98.50000
max    100.00000

In [11]:
pushpak = pd.read_csv('pushpak.csv') #to read the csv file

In [12]:
pushpak  #write the name of dataframe to print it

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,train no,speed,city
0,0,0,0,0,0,first,9090,50,indore
1,1,1,1,1,1,second,8989,98,ujjain
2,2,2,2,2,2,third,7777,97,dewas
3,3,3,3,3,3,forth,5555,100,bhopal

In [13]:
pushpak['speed'] #this print only speed coloumn

0     50
1     98
2     97
3    100
Name: speed, dtype: int64

In [14]:
int(pushpak['speed'][0]) #this specific coloumn element of specific index

50

In [15]:
pushpak.loc[0,'speed'] = 50 #this changes the value of particular element in dataframe directly

In [16]:
pushpak

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,train no,speed,city
0,0,0,0,0,0,first,9090,50,indore
1,1,1,1,1,1,second,8989,98,ujjain
2,2,2,2,2,2,third,7777,97,dewas
3,3,3,3,3,3,forth,5555,100,bhopal

In [17]:
pushpak.to_csv('pushpak.csv') #pushpak dataframe convert into csv file //to_csv is a function of pandas to save the dataframe into file

In [18]:
pushpak.index = ['first','second','third','forth']

In [19]:
pushpak

,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,train no,speed,city
first,0,0,0,0,0,first,9090,50,indore
second,1,1,1,1,1,second,8989,98,ujjain
third,2,2,2,2,2,third,7777,97,dewas
forth,3,3,3,3,3,forth,5555,100,bhopal

In [20]:
ser = pd.Series(np.random.rand(34))

In [21]:
ser

0     0.317108
1     0.360178
2     0.978018
3     0.752599
4     0.816093
5     0.208481
6     0.304115
7     0.294071
8     0.308242
9     0.033657
10    0.813711
11    0.822776
12    0.172367
13    0.995830
14    0.130623
15    0.815870
16    0.520708
17    0.966884
18    0.707110
19    0.821043
20    0.752936
21    0.406187
22    0.119540
23    0.128263
24    0.159731
25    0.987012
26    0.144748
27    0.605167
28    0.005600
29    0.898658
30    0.154592
31    0.427674
32    0.838589
33    0.697380
dtype: float64

In [22]:
type(ser)

pandas.Series

In [23]:
newdf = pd.DataFrame(np.random.rand(334,5) , index = np.arange(334))

In [24]:
newdf.head()

          0         1         2         3         4
0  0.069227  0.397055  0.229969  0.291435  0.431319
1  0.021221  0.724420  0.985917  0.167666  0.761428
2  0.270627  0.425891  0.252040  0.982825  0.676192
3  0.312291  0.125831  0.014697  0.608214  0.690924
4  0.674054  0.963439  0.208097  0.530244  0.445929

In [25]:
type(newdf)

pandas.DataFrame

In [26]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.474518    0.496961    0.503993    0.484587    0.506553
std      0.292575    0.292671    0.292627    0.282589    0.290677
min      0.002860    0.001265    0.001048    0.004839    0.003993
25%      0.218770    0.240615    0.252270    0.225326    0.228072
50%      0.435606    0.500576    0.512876    0.469106    0.536239
75%      0.732369    0.741855    0.759018    0.724375    0.756004
max      0.994398    0.998035    0.999533    0.996524    0.998799

In [27]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [28]:
newdf[0] = newdf[0].astype(object) #make[0,0] convert to object datatype

In [29]:
newdf.dtypes #shows datatypes of each column

0     object
1    float64
2    float64
3    float64
4    float64
dtype: object

In [30]:
newdf.iloc[0, 0] = "pushpak"  # insert pushpak in [0,0] cell

In [31]:
newdf.head()

          0         1         2         3         4
0   pushpak  0.397055  0.229969  0.291435  0.431319
1  0.021221  0.724420  0.985917  0.167666  0.761428
2  0.270627  0.425891  0.252040  0.982825  0.676192
3  0.312291  0.125831  0.014697  0.608214  0.690924
4  0.674054  0.963439  0.208097  0.530244  0.445929

In [32]:
newdf.index #shows indexs of each row

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [33]:
newdf.columns #shows length of coloumns

RangeIndex(start=0, stop=5, step=1)

In [34]:
newdf.to_numpy()

array([['pushpak', 0.3970553517587947, 0.22996878405675414,
        0.29143476929717727, 0.4313185972961424],
       [0.021221217191890185, 0.7244196457005614, 0.9859170872980632,
        0.16766597988228915, 0.7614279297594594],
       [0.2706268404372031, 0.42589059789422135, 0.2520404305511901,
        0.982825426193074, 0.6761920509859533],
       ...,
       [0.1587846931322967, 0.7077565096232681, 0.011351091510541367,
        0.30026491163296953, 0.9779184938627844],
       [0.7102601443325234, 0.0959806334836798, 0.12955310415960142,
        0.058130951790998475, 0.7813604102739586],
       [0.7572698310857999, 0.6871063982103749, 0.2211607554524283,
        0.5214453935314953, 0.11233218387894295]],
      shape=(334, 5), dtype=object)

In [35]:
newdf[0] = pd.to_numeric(newdf[0], errors = 'coerce') # converts to float safely (not necessary)
newdf.loc[0, 0] = 0.3

In [36]:
newdf.head()

          0         1         2         3         4
0  0.300000  0.397055  0.229969  0.291435  0.431319
1  0.021221  0.724420  0.985917  0.167666  0.761428
2  0.270627  0.425891  0.252040  0.982825  0.676192
3  0.312291  0.125831  0.014697  0.608214  0.690924
4  0.674054  0.963439  0.208097  0.530244  0.445929

In [37]:
newdf.T # transport rows and columns

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.300000,0.021221,0.270627,0.312291,0.674054,0.208337,0.712284,0.656627,0.639896,0.763341,...,0.882845,0.500636,0.002860,0.129875,0.236146,0.053030,0.433658,0.158785,0.710260,0.757270
1,0.397055,0.724420,0.425891,0.125831,0.963439,0.183015,0.627604,0.674860,0.318501,0.386315,...,0.049291,0.016897,0.095643,0.456920,0.865838,0.828326,0.718948,0.707757,0.095981,0.687106
2,0.229969,0.985917,0.252040,0.014697,0.208097,0.416209,0.410813,0.055507,0.097472,0.586284,...,0.700717,0.283478,0.135557,0.226717,0.945702,0.347491,0.737563,0.011351,0.129553,0.221161
3,0.291435,0.167666,0.982825,0.608214,0.530244,0.389253,0.236516,0.634370,0.597210,0.402561,...,0.654287,0.465311,0.628366,0.457098,0.419994,0.306854,0.612747,0.300265,0.058131,0.521445
4,0.431319,0.761428,0.676192,0.690924,0.445929,0.088530,0.688663,0.912792,0.136279,0.642981,...,0.198797,0.308073,0.756467,0.166032,0.678171,0.085166,0.063182,0.977918,0.781360,0.112332

In [38]:
newdf.sort_index(axis=0 , ascending=False) #axis=0 means rows yani rows me sorting krega 
#ascending=false isliye kuki by default sorting true hoti h 
#agr sort ni h to fr ascending = true likho

            0         1         2         3         4
333  0.757270  0.687106  0.221161  0.521445  0.112332
332  0.710260  0.095981  0.129553  0.058131  0.781360
331  0.158785  0.707757  0.011351  0.300265  0.977918
330  0.433658  0.718948  0.737563  0.612747  0.063182
329  0.053030  0.828326  0.347491  0.306854  0.085166
..        ...       ...       ...       ...       ...
4    0.674054  0.963439  0.208097  0.530244  0.445929
3    0.312291  0.125831  0.014697  0.608214  0.690924
2    0.270627  0.425891  0.252040  0.982825  0.676192
1    0.021221  0.724420  0.985917  0.167666  0.761428
0    0.300000  0.397055  0.229969  0.291435  0.431319

[334 rows x 5 columns]

In [39]:
newdf.sort_index(axis=1,ascending=False) #axis=1 means column me sorting krega

            4         3         2         1         0
0    0.431319  0.291435  0.229969  0.397055  0.300000
1    0.761428  0.167666  0.985917  0.724420  0.021221
2    0.676192  0.982825  0.252040  0.425891  0.270627
3    0.690924  0.608214  0.014697  0.125831  0.312291
4    0.445929  0.530244  0.208097  0.963439  0.674054
..        ...       ...       ...       ...       ...
329  0.085166  0.306854  0.347491  0.828326  0.053030
330  0.063182  0.612747  0.737563  0.718948  0.433658
331  0.977918  0.300265  0.011351  0.707757  0.158785
332  0.781360  0.058131  0.129553  0.095981  0.710260
333  0.112332  0.521445  0.221161  0.687106  0.757270

[334 rows x 5 columns]

In [40]:
newdf.head()

          0         1         2         3         4
0  0.300000  0.397055  0.229969  0.291435  0.431319
1  0.021221  0.724420  0.985917  0.167666  0.761428
2  0.270627  0.425891  0.252040  0.982825  0.676192
3  0.312291  0.125831  0.014697  0.608214  0.690924
4  0.674054  0.963439  0.208097  0.530244  0.445929

In [41]:
newdf[0]

0      0.300000
1      0.021221
2      0.270627
3      0.312291
4      0.674054
         ...
329    0.053030
330    0.433658
331    0.158785
332    0.710260
333    0.757270
Name: 0, Length: 334, dtype: float64

In [42]:
type(newdf[0])

pandas.Series

In [43]:
newdf2 = newdf #iska mtlb newdf dusra ni bana // newdf2 ek view h newdf ka //basically acts as pointer
# if wwe change something in newdf2 so it changes in newdf also

In [44]:
newdf2.loc[0, 0] = 9783

In [45]:
newdf.head()

             0         1         2         3         4
0  9783.000000  0.397055  0.229969  0.291435  0.431319
1     0.021221  0.724420  0.985917  0.167666  0.761428
2     0.270627  0.425891  0.252040  0.982825  0.676192
3     0.312291  0.125831  0.014697  0.608214  0.690924
4     0.674054  0.963439  0.208097  0.530244  0.445929

In [46]:
newdf2 = newdf.copy() # ye ek fuction h jisse newdf ki ek copy ban jayegi

In [47]:
newdf2.loc[0, 0] = 97839 # but if we change something in newdf so it doesnt change in newdf bcz its a copy not a view

In [48]:
newdf.head()

             0         1         2         3         4
0  9783.000000  0.397055  0.229969  0.291435  0.431319
1     0.021221  0.724420  0.985917  0.167666  0.761428
2     0.270627  0.425891  0.252040  0.982825  0.676192
3     0.312291  0.125831  0.014697  0.608214  0.690924
4     0.674054  0.963439  0.208097  0.530244  0.445929

In [49]:
newdf.columns = list("ABCDE") #converts columns naming to abcde

In [50]:
newdf.head(2)

             A         B         C         D         E
0  9783.000000  0.397055  0.229969  0.291435  0.431319
1     0.021221  0.724420  0.985917  0.167666  0.761428

In [51]:
newdf.loc[0, 0] = 1090   #after changing column to alphabet ,
                        #Now if we want to change the value of [0, 0] into 1090 so it doesnt change
                        #ye error ni dega instead ye ek new columns bana dega zero karke cz column sare alphabetic form me h

In [52]:
newdf.head(5) # like that new zero column

             A         B         C         D         E       0
0  9783.000000  0.397055  0.229969  0.291435  0.431319  1090.0
1     0.021221  0.724420  0.985917  0.167666  0.761428     NaN
2     0.270627  0.425891  0.252040  0.982825  0.676192     NaN
3     0.312291  0.125831  0.014697  0.608214  0.690924     NaN
4     0.674054  0.963439  0.208097  0.530244  0.445929     NaN

In [53]:
newdf.loc[0, 'A'] = 97835

In [54]:
newdf.head(5)

              A         B         C         D         E       0
0  97835.000000  0.397055  0.229969  0.291435  0.431319  1090.0
1      0.021221  0.724420  0.985917  0.167666  0.761428     NaN
2      0.270627  0.425891  0.252040  0.982825  0.676192     NaN
3      0.312291  0.125831  0.014697  0.608214  0.690924     NaN
4      0.674054  0.963439  0.208097  0.530244  0.445929     NaN

In [55]:
newdf = newdf.drop(0 , axis=1) # drop is a function to delete any row or column by giving the axis 1 or 2

In [56]:
newdf.head(5)

              A         B         C         D         E
0  97835.000000  0.397055  0.229969  0.291435  0.431319
1      0.021221  0.724420  0.985917  0.167666  0.761428
2      0.270627  0.425891  0.252040  0.982825  0.676192
3      0.312291  0.125831  0.014697  0.608214  0.690924
4      0.674054  0.963439  0.208097  0.530244  0.445929

In [57]:
newdf.loc[[1,2] , ['C' , 'D']]

          C         D
1  0.985917  0.167666
2  0.252040  0.982825

In [60]:
newdf.loc[: , ['C', 'D']]   #if we want all rows but particular columns so we put : 'colon' first , then particular column index

            C         D
0    0.229969  0.291435
1    0.985917  0.167666
2    0.252040  0.982825
3    0.014697  0.608214
4    0.208097  0.530244
..        ...       ...
329  0.347491  0.306854
330  0.737563  0.612747
331  0.011351  0.300265
332  0.129553  0.058131
333  0.221161  0.521445

[334 rows x 2 columns]

In [62]:
#if we want all columns but particular rows so we put particular row index first then : 'colon'
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.021221  0.724420  0.985917  0.167666  0.761428
2  0.270627  0.425891  0.252040  0.982825  0.676192

In [66]:
newdf.loc[(newdf['A']<0.3) & (newdf['C']>0.1)]  # print things from column A which are smaller than 0.3 and
                                                # in c which are greater than 0.1

            A         B         C         D         E
1    0.021221  0.724420  0.985917  0.167666  0.761428
2    0.270627  0.425891  0.252040  0.982825  0.676192
5    0.208337  0.183015  0.416209  0.389253  0.088530
11   0.149327  0.854093  0.207103  0.331725  0.003993
12   0.134862  0.151241  0.275714  0.808096  0.522720
..        ...       ...       ...       ...       ...
323  0.160400  0.435663  0.899552  0.127418  0.886500
326  0.002860  0.095643  0.135557  0.628366  0.756467
327  0.129875  0.456920  0.226717  0.457098  0.166032
328  0.236146  0.865838  0.945702  0.419994  0.678171
329  0.053030  0.828326  0.347491  0.306854  0.085166

[107 rows x 5 columns]

In [67]:
newdf.head()

              A         B         C         D         E
0  97835.000000  0.397055  0.229969  0.291435  0.431319
1      0.021221  0.724420  0.985917  0.167666  0.761428
2      0.270627  0.425891  0.252040  0.982825  0.676192
3      0.312291  0.125831  0.014697  0.608214  0.690924
4      0.674054  0.963439  0.208097  0.530244  0.445929

In [68]:
newdf.iloc[0, 4]  # iloc is used when mujhe index se ginti krni ho despite from the name of the column
                  #loc is used when apko ginti ni krni and particular colomn ya row ka name deke data chiye

np.float64(0.4313185972961424)

In [69]:
newdf.head(5)   # here newdf is a copy or a newdata frame cz we do above newdf= newdf.drop like that 
                #it didnt change the original data

              A         B         C         D         E
0  97835.000000  0.397055  0.229969  0.291435  0.431319
1      0.021221  0.724420  0.985917  0.167666  0.761428
2      0.270627  0.425891  0.252040  0.982825  0.676192
3      0.312291  0.125831  0.014697  0.608214  0.690924
4      0.674054  0.963439  0.208097  0.530244  0.445929

In [73]:
# but there is function called inplace which remove the data from the original dataframe
newdf.drop([1,5], axis=0 , inplace= True)

In [74]:
newdf

            B         C         E
0    0.397055  0.229969  0.431319
2    0.425891  0.252040  0.676192
3    0.125831  0.014697  0.690924
4    0.963439  0.208097  0.445929
6    0.627604  0.410813  0.688663
..        ...       ...       ...
329  0.828326  0.347491  0.085166
330  0.718948  0.737563  0.063182
331  0.707757  0.011351  0.977918
332  0.095981  0.129553  0.781360
333  0.687106  0.221161  0.112332

[332 rows x 3 columns]

In [79]:
# now above the index of rows starts like 0,2,3,4,6 and if we want to reset it like 0,1,2,3,4,5,6
# so there is function called reset_index()
newdf.reset_index() # it resets the index but it add the another column named index which we dont want 
# we use 
newdf.reset_index(drop=True, inplace=True)

In [81]:
newdf.head(3)

          B         C         E
0  0.397055  0.229969  0.431319
1  0.425891  0.252040  0.676192
2  0.125831  0.014697  0.690924